import { UpdatedPlayer } from "../types/teamsAndPlayers";

export const players: UpdatedPlayer[] = [
  {
    userId: "402331217",
    username: "Mike M",
    nickname: "Mike M",
    firstName: "Михайло",
    lastName: "Михасяк",
    tier: "CORE",
  },
  {
    userId: "314792024",
    username: "forn1cation",
    nickname: "forn1cation",
    firstName: "Андрій",
    lastName: "Співак",
    tier: "OK",
  },
  {
    userId: "708964766",
    username: "rabotiahov",
    nickname: "Dmytro️ Rabotiahov",
    firstName: "Дмитро",
    lastName: "Работягов",
    tier: "R",
  },
  {
    userId: "5227978638",
    username: "",
    nickname: "Roman Maksymets",
    firstName: "Роман",
    lastName: "Максимець",
    tier: "GC",
  },
  {
    userId: "5113285864",
    username: "",
    nickname: "Сашко Страшевський",
    firstName: "Сашко",
    lastName: "Страшевський",
    tier: "R",
  },
  {
    userId: "531159114",
    username: "",
    nickname: "Ievhen Kost",
    firstName: "Євген",
    lastName: "Кость",
    tier: "GC",
  },
  {
    userId: "1207008062",
    username: "therion2901",
    nickname: "Yuriy Tychenko",
    firstName: "Юрій",
    lastName: "Тиченко",
    tier: "CORE",
  },
  {
    userId: "918736429",
    username: "",
    nickname: "Oleksandr Pavlichko",
    firstName: "Олександр",
    lastName: "Павлічко",
    tier: "CORE",
  },
  {
    userId: "798195161",
    username: "",
    nickname: "Андрій С",
    firstName: "Андрій",
    lastName: "Согор",
    tier: "OK",
  },
  {
    userId: "366405369",
    username: "illiamishchenko",
    nickname: "Illia M",
    firstName: "Ілля",
    lastName: "Міщенко",
    tier: "CORE",
  },
  {
    userId: "381606695",
    username: "NazarYar21",
    nickname: "Nazar",
    firstName: "Назарій",
    lastName: "Яремчук",
    tier: "OK",
  },
  {
    userId: "533763627",
    username: "",
    nickname: "P T",
    firstName: "Петро",
    lastName: "Тераз",
    tier: "GC",
  },
  {
    userId: "554685414",
    username: "",
    nickname: "Volodymyr N",
    firstName: "Володимир",
    lastName: "Нищий",
    tier: "OK",
  },
  {
    userId: "488105134",
    username: "Oleksandr_Olistener",
    nickname: "Oleksandr Kuharchuk",
    firstName: "Олександр",
    lastName: "Кухарчук",
    tier: "CORE",
  },
  {
    userId: "622974859",
    username: "",
    nickname: "Володимир Українець",
    firstName: "Володимир",
    lastName: "Українець",
    tier: "OK",
  },
  {
    userId: "761553633",
    username: "bodkol",
    nickname: "Bodya",
    firstName: "Богдан",
    lastName: "???",
    tier: "OK",
  },
  {
    userId: "349489768",
    username: "andrijpank",
    nickname: "Pankiv Andrii",
    firstName: "Голова",
    lastName: "і два вуха",
    tier: "OK",
  },
  {
    userId: "410720492",
    username: "victorshulhin",
    nickname: "Victor Shulhin",
    firstName: "",
    lastName: "",
    tier: "R",
  },
  {
    userId: "335399748",
    username: "n_yurchenko",
    nickname: "Nazar Yurchenko",
    firstName: "Назар",
    lastName: "Юрченко",
    tier: "OK",
  },
  {
    userId: "665558423",
    username: "rostyk_kar",
    nickname: "Ростислав Карабінович",
    firstName: "Ростик",
    lastName: "Карабінович",
    tier: "CORE",
  },
  {
    userId: "6649322644",
    username: "",
    nickname: "IvanKep",
    firstName: "Іван",
    lastName: "Кондратюк",
    tier: "R",
  },
  {
    userId: "1137091526",
    username: "",
    nickname: "Oleh Demkiv",
    firstName: "Олег",
    lastName: "Демків",
    tier: "OK",
  },
  {
    userId: "542864571",
    username: "",
    nickname: "Михайло",
    firstName: "Михайло",
    lastName: "Хабурський",
    tier: "CORE",
  },
  {
    userId: "1454312816",
    username: "oturch",
    nickname: "Oleg Turych",
    firstName: "Олег",
    lastName: "Турич",
    tier: "OK",
  },
  {
    userId: "481099043",
    username: "BIZONym",
    nickname: "Юрко Музика",
    firstName: "Юрко",
    lastName: "Музика",
    tier: "CORE",
  },
  {
    userId: "254813951",
    username: "em0gene",
    nickname: "Eugene",
    firstName: "Євгеній",
    lastName: "Кулинич",
    tier: "OK",
  },
  {
    userId: "634708535",
    username: "Vitalix21",
    nickname: "Vitalik",
    firstName: "Віталій",
    lastName: "Маланкевич",
    tier: "GC",
  },
  {
    userId: "560437367",
    username: "AndriyBernatskiy",
    nickname: "Andriy Bernatskiy",
    firstName: "Андрій",
    lastName: "Бернацький",
    tier: "CORE",
  },
  {
    userId: "6883825308",
    username: "biltarik",
    nickname: "Taras",
    firstName: "Тарас",
    lastName: "Білинець",
    tier: "CORE",
  },
  {
    userId: "1022353388",
    username: "nick_frost",
    nickname: "Nick Frost",
    firstName: "Микола",
    lastName: "Мороз",
    tier: "OK",
  },
  {
    userId: "1017989432",
    username: "GeorgeRed1886",
    nickname: "George🦖 Utinkevich",
    firstName: "George",
    lastName: "Utinkevich",
    tier: "OK",
  },
  {
    userId: "782158202",
    username: "kobylinets",
    nickname: "Іван Кобилінець",
    firstName: "Іван",
    lastName: "Кобилінець",
    tier: "OK",
  },
];
